# Generated by Django 5.0.1 on 2024-01-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuckit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="datecompleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
